### ISSUE TITLE
Vertaisiarviointi1

### ISSUE THREAD

**Issue by veeranniina** [shdewz/tsoha-forum-webapp#1]
Kloonasin repon koneelleni ja tein tarvittavat toimet sovelluksen käynnistämiseksi. Sovellusta ei harmillisesti kuitenkaan saanut toimimaan: "Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application". Joten en pystynyt arvioimaan sovellusta käyttäjän näkökulmasta. 

Tutustuin kuitenkin jo luotuun koodiin, joka näyttää minun silmään hyvältä. Löytyy tiedosto app.py, jossa on käytetty hyvin SQL-komentoja. Tietokannassa näkyy olevan luotuna useampi taulu ja tietokannan rakenne vaikuttaa hyvältä. Myös .gitignore löytyy, hyvä! Ulkoasuakin on jo mietitty.Vinkkinä tulevaisuutta ajatellen: muista jakaa koodi osiin moduuleiksi. 

Sovellus vaikuttaa olevan hyvällä alulla, nyt vain luomaan uusia moduuleja. Tsemppiä!

**Comment by shdewz** [comment]
Tämä virhe nähtävästi johtui siitä, että dokumentaatiosta unohtui maininta salausavaimesta `SECRET` `.env`-tiedostossa. Avaimen lisäämisen jälkeen sovelluksen pitäisi käynnistyä.
