### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by CaseEight** [shdewz/tsoha-forum-webapp#2]
- Käyttäjä voi kirjautua sisään ja ulos sekä luoda uuden tunnuksen
Toimii. Ei liian lyhyt tai pitkä käyttäjä nimi, ei XSS-haavoittuvuutta.
- Käyttäjä näkee sovelluksen etusivulla listan alueista sekä jokaisen alueen ja ketjun viimeksi lähetetyn viestin ajankohdan
Toimii
- Käyttäjä voi selata alueita ja ketjuja
Toimii
- Käyttäjä voi luoda alueelle uuden ketjun antamalla ketjun otsikon ja aloitusviestin sisällön
Toimii
- Käyttäjä voi kirjoittaa uuden viestin olemassa olevaan ketjuun
Kun käyttäjä syöttää liian pitkän viestin niin voisi tulla jokin ilmoitus. Nyt viestiä vain ei postata.
- Käyttäjä voi poistaa lähettämänsä viestin tai ketjun
Toimii
- Sovellus on tyylitelty
CSS tyylittely erittäin ansiokasta ja hyvännäköistä! Nähty vaivaa.

Bugeja en löytänyt sovellusta testatessa. Puolestaan koodi on yleisilmeeltä selkeää ja hyvin jäsenneltyä ja helppolukuista. Mielestäni tuosta löytyi vielä CSRF-haavoittuvuus, tästä tulee luultavasti assariltakin kommenttia.

Users-taulussa käyttäjäryhmän voisi määritellä IsAdmin True/False tyyppisesti, nyt kokonaisluvulla, en tiedä voiko tästä koitua ongelmia. Toisaalta jos mielessäsi on useampiakin käyttäjäryhmiä niin miksi ei. Ylläpitäjän määrittelylle puuttuu vielä ominaisuudet, mutta nämä tulevat varmaan viimeiseen versioon. Readmessa annetuilla ohjeilla sai sovelluksen hyvin käyntiin.

**Comment by shdewz** [comment]
Kiitos palautteesta! Tuossa käyttäjäryhmässä tosiaan oli alunperin ideana useampi ryhmä, mutta niiden jäätyä pois suunnitelmista True/False tyyppinen käytäntö toimisi paremmin, hyvä huomio. Ylläpito-ominaisuudet myös arvatusti jäivät tällä kertaa ensi viikon murheiksi.

Hyvä huomio myös CSRF:stä, tuo oli jo aikaisemmin tarkoitus korjailla, mutta näyttänee jääneen välistä.
